**Chapter 04 - Subqueries - Exercises**

**Q5**
```SQL
-- Write a query that returns for each customer

-- all orders placed on the customer's last day of activity

-- Tables involved: TSQLV6 database, Orders table
```

### Proposition
This query retrieves the latest order for each customer in the `Northwinds2022TSQLV7` database. It selects the `CustomerId`, `OrderId`, `OrderDate`, and `EmployeeId` from the `Sales.Order` table for orders where the `OrderDate` is equal to the maximum `OrderDate` for each customer.

### Tables and Columns Used
- **Table**: `Sales.Order`
- **Columns**: `CustomerId`, `OrderId`, `OrderDate`, `EmployeeId`

### Explanation
- **Subquery**: The subquery `(SELECT MAX(o2.OrderDate) FROM Sales.[Order] as o2 WHERE o2.CustomerId = o.CustomerId)` calculates the maximum `OrderDate` for each `CustomerId`.
- **Main Query**: The main query then filters the rows from the `Sales.Order` table to include only those with an `OrderDate` equal to the maximum `OrderDate` for each customer, effectively retrieving the latest order for each customer.
- **Result Set**: The query generates a result set where each row contains the `CustomerId`, `OrderId`, `OrderDate`, and `EmployeeId` for the latest order of each customer, ordered by `CustomerId`.

In [ ]:
USE [TSQLV6]
go

SELECT o.custid, o.orderid, o.orderdate, o.empid
FROM Sales.[Orders] as o
WHERE o.orderdate = (
    SELECT MAX(o2.orderdate)
    FROM Sales.[Orders] as o2
    WHERE o2.custid = o.custid
)
ORDER BY o.custid;

USE [Northwinds2022TSQLV7]
go

SELECT o.CustomerId, o.OrderId, o.OrderDate, o.EmployeeId
FROM Sales.[Order] as o
WHERE o.OrderDate = (
    SELECT MAX(o2.OrderDate)
    FROM Sales.[Order] as o2
    WHERE o2.CustomerId = o.CustomerId
)
ORDER BY o.CustomerId;

**Chapter 04 - Subqueries - Exercises**

**Q6**

-- Write a query that returns customers

-- who placed orders in 2021 but not in 2022

-- Tables involved: TSQLV6 database, Customers and Orders tables

-- Desired output:
```sql
custid      companyname
----------- ----------------------------------------
21          Customer KIDPX
23          Customer WVFAF
33          Customer FVXPQ
36          Customer LVJSO
43          Customer UISOJ
51          Customer PVDZC
85          Customer ENQZT
```
### Proposition
This query retrieves customers from the `Sales.Customer` table in the `Northwinds2022TSQLV7` database who placed orders in 2021 but not in 2022. It selects the `CustomerId` and `CustomerCompanyName` from the `Sales.Customer` table where the `CustomerId` is in the list of customers who placed orders in 2021 but not in 2022.

### Tables and Columns Used
- **Table**: `Sales.Customer`, `Sales.Order`
- **Columns**: `CustomerId`, `CustomerCompanyName` (from `Sales.Customer`), `OrderDate` (from `Sales.Order`)

### Explanation
- **Subqueries**: 
  - The first subquery `(SELECT o.CustomerId FROM Sales.[Order] as o WHERE o.OrderDate >= '20210101' and o.OrderDate < '20220101')` retrieves the `CustomerId` of customers who placed orders in 2021.
  - The second subquery `(SELECT o.CustomerId FROM Sales.[Order] as o WHERE o.OrderDate >= '20220101' and o.OrderDate < '20230101')` retrieves the `CustomerId` of customers who placed orders in 2022.
- **Main Query**: 
  - The main query then filters the rows from the `Sales.Customer` table to include only those whose `CustomerId` is in the first subquery (i.e., customers who placed orders in 2021) but not in the second subquery (i.e., customers who placed orders in 2022), effectively retrieving customers who placed orders in 2021 but not in 2022.
- **Result Set**: 
  - The query generates a result set where each row contains the `CustomerId` and `CustomerCompanyName` for customers who placed orders in 2021 but not in 2022.

**NOTE:**
- in Northwinds2022TSQLV7 for all orders, the order dates are in range of `2014-07-04` to `2016-05-06`

- so there is `no output` from Northwinds2022TSQLV7

In [ ]:
USE [TSQLV6]
GO
SELECT 'In TSQLV6',MIN(o.OrderDate), MAX(o.OrderDate)
FROM Sales.[Orders] as o

USE [Northwinds2022TSQLV7]
GO
SELECT 'In Northwinds2022TSQLV7',MIN(o.OrderDate), MAX(o.OrderDate)
FROM Sales.[Order] as o

In [ ]:
USE [TSQLV6]
go

SELECT c.custid, c.companyname
FROM Sales.[Customers] as c
WHERE c.custid  IN (
    SELECT o.custid
    FROM Sales.[Orders] as o
    WHERE o.orderdate >= '20210101' and o.orderdate < '20220101'
)
AND c.custid NOT IN (
    SELECT o.custid
    FROM Sales.[Orders] as o
    WHERE o.orderdate >= '20220101' and o.orderdate < '20230101'
);

USE [Northwinds2022TSQLV7]
go

SELECT c.CustomerId, c.CustomerCompanyName
FROM Sales.[Customer] as c
WHERE c.CustomerId  IN (
    SELECT o.CustomerId
    FROM Sales.[Order] as o
    WHERE o.OrderDate >= '20210101' and o.OrderDate < '20220101'
)
AND c.CustomerId NOT IN (
    SELECT o.CustomerId
    FROM Sales.[Order] as o
    WHERE o.OrderDate >= '20220101' and o.OrderDate < '20230101'
);

**Chapter 04 - Subqueries**

**EXISTS - 1**

### Question

- Customers from Spain who placed orders

### Proposition

This query retrieves the customer ID (`CustomerId`) and company name (`CustomerCompanyName`) from the `Sales.Customer` table for customers located in Spain (`CustomerCountry = N'Spain'`) who have placed orders. It uses a correlated subquery with `EXISTS` to check for the existence of orders for each customer.

### Table and Columns used

- **Table**: `Sales.Customer` (aliased as `C`)
- **Columns**: `CustomerId`, `CustomerCompanyName`

### Predicate

- **Main Query**: Filters customers based on the `CustomerCountry` column (`CustomerCountry = N'Spain'`).
- **Subquery**: Checks for the existence of orders for each customer (`O.CustomerId = C.CustomerId`).

### Explanation

1. **Main Query**: The `Sales.Customer` table is aliased as `C`. It selects `CustomerId` and `CustomerCompanyName` columns for customers located in Spain (`CustomerCountry = N'Spain'`).
    
2. **Subquery**: For each row in the main query's result set, the subquery is executed. It selects any row from the `Sales.Order` table (`Sales.Order AS O`) where the `CustomerId` matches the `CustomerId` of the current row in the main query (`O.CustomerId = C.CustomerId`). This correlated subquery ensures that only customers with orders are included in the final result
    

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
go

SELECT custid, companyname
FROM Sales.Customers AS C
WHERE country = N'Spain'
  AND EXISTS
    (SELECT * FROM Sales.Orders AS O
     WHERE O.custid = C.custid);

USE [Northwinds2022TSQLV7]
go

SELECT c.CustomerId, c.CustomerCompanyName
FROM [Sales].[Customer] AS C
WHERE c.CustomerCountry = N'Spain'
  AND EXISTS
    (SELECT * FROM [Sales].[Order] AS O
     WHERE O.CustomerId = C.CustomerId);

**Chapter 04 - Subqueries**

**EXISTS - 2**

### Question
- Customers from Spain who didn't place Orders

### Proposition
This query retrieves the customer ID (`CustomerId`) and company name (`CustomerCompanyName`) from the `Sales.Customer` table for customers located in Spain (`CustomerCountry = N'Spain'`) who have not placed any orders. It uses a correlated subquery with `NOT EXISTS` to check for the absence of orders for each customer.

### Table and Columns used
- **Table**: `Sales.Customer` (aliased as `C`)
- **Columns**: `CustomerId`, `CustomerCompanyName`

### Predicate
- **Main Query**: Filters customers based on the `CustomerCountry` column (`CustomerCountry = N'Spain'`).
- **Subquery**: Checks for the absence of orders for each customer (`O.CustomerId = C.CustomerId`).

### Explanation
1. **Main Query**: The `Sales.Customer` table is aliased as `C`. It selects `CustomerId` and `CustomerCompanyName` columns for customers located in Spain (`CustomerCountry = N'Spain'`).

2. **Subquery**: For each row in the main query's result set, the subquery is executed. It selects any row from the `Sales.Order` table (`Sales.Order AS O`) where the `CustomerId` matches the `CustomerId` of the current row in the main query (`O.CustomerId = C.CustomerId`). The `NOT EXISTS` condition ensures that only customers without orders are included in the final result.

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
go

SELECT custid, companyname
FROM Sales.Customers AS C
WHERE country = N'Spain'
  AND NOT EXISTS
    (SELECT * FROM Sales.Orders AS O
     WHERE O.custid = C.custid);

USE [Northwinds2022TSQLV7]
go

SELECT c.CustomerId, c.CustomerCompanyName
FROM [Sales].[Customer] AS C
WHERE c.CustomerCountry = N'Spain'
  AND NOT EXISTS
    (SELECT * FROM [Sales].[Order] AS O
     WHERE O.CustomerId = C.CustomerId);

**Chapter 04 - Subqueries**

**Returning "Previous" or "Next" Value - 1**

### Proposition
This query retrieves order information from the `Sales.Order` table, including the order ID (`OrderId`), order date (`OrderDate`), employee ID (`EmployeeId`), and customer ID (`CustomerId`). Additionally, it includes the previous order ID (`prevorderid`), which is the maximum order ID that is less than the current order ID. This is achieved using a correlated subquery to find the maximum order ID from the same table where the order ID is less than the current order ID.

### Table and Columns used
- **Table**: `Sales.Order` (aliased as `O1`)
- **Columns**: `OrderId`, `OrderDate`, `EmployeeId`, `CustomerId`

### Subquery
- The subquery selects the maximum order ID from the `Sales.Order` table aliased as `O2`, where the order ID is less than the current order ID.

### Explanation
1. **Main Query**: The main query selects the order ID, order date, employee ID, and customer ID from the `Sales.Order` table aliased as `O1`.

2. **Subquery**: For each row in the main query's result set, the subquery is executed to find the maximum order ID from the `Sales.Order` table aliased as `O2`, where the order ID is less than the current order ID. This gives the previous order ID for each order.

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
go

SELECT orderid, orderdate, empid, custid,
  (SELECT MAX(O2.orderid)
   FROM Sales.Orders AS O2
   WHERE O2.orderid < O1.orderid) AS prevorderid
FROM Sales.Orders AS O1;


USE [Northwinds2022TSQLV7]
go

SELECT O1.OrderId, O1.OrderDate, O1.EmployeeId, O1.CustomerId,
  (SELECT MAX(O2.OrderId)
   FROM [Sales].[Order] AS O2
   WHERE O2.OrderId < O1.OrderId) AS prevorderid
FROM [Sales].[Order] AS O1;

**Chapter 04 - Subqueries**

**Returning "Previous" or "Next" Value - 2**

### Proposition
This query retrieves order information from the `Sales.Order` table, including the order ID (`OrderId`), order date (`OrderDate`), employee ID (`EmployeeId`), and customer ID (`CustomerId`). Additionally, it includes the next order ID (`NextOrderid`), which is the minimum order ID that is greater than the current order ID. This is achieved using a correlated subquery to find the minimum order ID from the same table where the order ID is greater than the current order ID.

### Table and Columns used
- **Table**: `Sales.Order` (aliased as `O1`)
- **Columns**: `OrderId`, `OrderDate`, `EmployeeId`, `CustomerId`

### Subquery
- The subquery selects the minimum order ID from the `Sales.Order` table aliased as `O2`, where the order ID is greater than the current order ID.

### Explanation
1. **Main Query**: The main query selects the order ID, order date, employee ID, and customer ID from the `Sales.Order` table aliased as `O1`.

2. **Subquery**: For each row in the main query's result set, the subquery is executed to find the minimum order ID from the `Sales.Order` table aliased as `O2`, where the order ID is greater than the current order ID. This gives the next order ID for each order.

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
go

SELECT orderid, orderdate, empid, custid,
  (SELECT MIN(O2.orderid)
   FROM Sales.Orders AS O2
   WHERE O2.orderid > O1.orderid) AS nextorderid
FROM Sales.Orders AS O1;

USE [Northwinds2022TSQLV7]
go

SELECT O1.OrderId, O1.OrderDate, O1.EmployeeId, O1.CustomerId,
  (SELECT MIN(O2.OrderId)
   FROM [Sales].[Order] AS O2
   WHERE O2.OrderId > O1.OrderId) AS NextOrderid
FROM [Sales].[Order] AS O1;

**Chapter 04 - Subqueries**

**Running Aggregates - 1**

### Proposition
This query retrieves the `OrderYear` and `Quantity` columns from the `Sales.OrderTotalsByYear` view.

### Table and Columns used
- **View**: `Sales.OrderTotalsByYear`
- **Columns**: `OrderYear`, `Quantity`

### Predicate
- No explicit predicate is specified in the query. It simply selects `OrderYear` and `Quantity` columns from the `Sales.OrderTotalsByYear` view.

### Explanation
1. **Main Query**: The query selects the `OrderYear` and `Quantity` columns from the `Sales.OrderTotalsByYear` view.

### Note:
- In `Northwinds2022TSQLV7`, it does not exit such view `Sales.OrderTotalsByYear`, I took the view creation from `TSQLV6` and modifed it into `Northwinds2022TSQLV7`

- code show in below 


<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
use [Northwinds2022TSQLV7]
GO

IF OBJECT_ID('Sales.OrderTotalsByYear', 'V') IS NOT NULL
DROP VIEW Sales.OrderTotalsByYear;
GO

CREATE VIEW Sales.OrderTotalsByYear
  WITH SCHEMABINDING
AS

SELECT
  YEAR(O.OrderDate) AS OrderYear,
  SUM(OD.Quantity) AS Quantity
FROM [Sales].[Order] AS O
  JOIN [Sales].[OrderDetail] AS OD
    ON OD.OrderId = O.OrderId
GROUP BY YEAR(O.OrderDate);
GO

In [ ]:
use [TSQLV6]
go

SELECT orderyear, qty
FROM Sales.OrderTotalsByYear;

use [Northwinds2022TSQLV7]
go

SELECT x.OrderYear, x.Quantity
FROM [Sales].[OrderTotalsByYear] as x;

**Chapter 04 - Subqueries**

**Running Aggregates - 2**

### Proposition
This query calculates a running total of the `Quantity` column from the `Sales.OrderTotalsByYear` view. It retrieves the `OrderYear` and `Quantity` columns from the view, and for each row, it calculates the sum of `Quantity` for all years up to and including the current `OrderYear`.

### View and Columns used
- **view**: `Sales.OrderTotalsByYear` (used as `O1` and `O2`)
- **Columns**: `OrderYear`, `Quantity`

### Predicate
- The main query calculates the running total of `Quantity` for each `OrderYear`, summing up the quantities for all years up to and including the current `OrderYear`.

### Explanation
1. **Main Query**: The main query selects `OrderYear`, `Quantity`, and a running total (`runqty`) for each `OrderYear`. For each row, it calculates the sum of `Quantity` for all years up to and including the current `OrderYear`.

2. **Subquery**: The subquery calculates the running total (`SUM(O2.Quantity)`) for each `OrderYear` in the `Sales.OrderTotalsByYear` view (`O2`), where the `OrderYear` is less than or equal to the `OrderYear` of the current row in the main query (`O2.OrderYear <= O1.OrderYear`).

### Note:
- In `Northwinds2022TSQLV7`, it does not exit such view `Sales.OrderTotalsByYear`, I took the view creation from `TSQLV6` and modifed it into `Northwinds2022TSQLV7`

- code show in above 


<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
use [TSQLV6]
go

SELECT orderyear, qty,
  (SELECT SUM(O2.qty)
   FROM Sales.OrderTotalsByYear AS O2
   WHERE O2.orderyear <= O1.orderyear) AS runqty
FROM Sales.OrderTotalsByYear AS O1
ORDER BY orderyear;

use [Northwinds2022TSQLV7]
go

SELECT  O1.OrderYear, O1.Quantity,
  (SELECT SUM(O2.Quantity)
   FROM [Sales].[OrderTotalsByYear] AS O2
   WHERE O2.OrderYear <= O1.OrderYear) AS runqty
FROM [Sales].[OrderTotalsByYear] AS O1
ORDER BY O1.OrderYear;

**Chapter 05 - Table Expressions - Exercises**

**5.1**

```
-- Create a view that returns the total qty
-- for each employee and year
-- Tables involved: Sales.Orders and Sales.OrderDetails

-- Desired output when running:
-- SELECT * FROM  Sales.VEmpOrders ORDER BY empid, orderyear
empid       orderyear   qty
----------- ----------- -----------
1           2020        1620
1           2021        3877
1           2022        2315
2           2020        1085
2           2021        2604
2           2022        2366
3           2020        940
3           2021        4436
3           2022        2476
4           2020        2212
4           2021        5273
4           2022        2313
5           2020        778
5           2021        1471
5           2022        787
6           2020        963
6           2021        1738
6           2022        826
7           2020        485
7           2021        2292
7           2022        1877
8           2020        923
8           2021        2843
8           2022        2147
9           2020        575
9           2021        955
9           2022        1140
```

### Proposition
This script drops the existing view `Sales.VEmpOrder` if it exists and then creates or alters the view to include data from the `Sales.Order` and `Sales.OrderDetail` tables. The view calculates the total quantity of products ordered by each employee (`EmployeeId`) for each year (`OrderYear`), grouping the results by `EmployeeId` and `OrderYear`.

### Tables used
- **Tables**: `Sales.Order`, `Sales.OrderDetail`

### Columns used
- **Columns**: `EmployeeId`, `OrderDate`, `Quantity`

### Explanation
1. **Drop View**: The script first checks if the view `Sales.VEmpOrder` exists. If it does, the view is dropped using the `DROP VIEW` statement.

2. **Create or Alter View**: The script then creates or alters the view `Sales.VEmpOrder` to include the `EmployeeId`, `OrderYear` (derived from `OrderDate` using `YEAR()` function), and the total quantity of products ordered (`Quantity`) for each employee and year. The data is obtained by joining the `Sales.Order` and `Sales.OrderDetail` tables o


<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
use [TSQLV6]
GO

IF OBJECT_ID('Sales.VEmpOrders', 'V') IS NOT NULL
DROP VIEW Sales.VEmpOrders;
GO

CREATE OR ALTER VIEW [Sales].[VEmpOrders]
  WITH SCHEMABINDING
AS

SELECT
  empid,
  YEAR(O.orderdate) AS orderyear,
  SUM(OD.qty) AS qty
FROM [Sales].[Orders] AS O
  JOIN [Sales].[OrderDetails] AS OD
    ON OD.orderid = O.orderid
GROUP BY 
  empid,
  YEAR(O.orderdate);
GO

SELECT * FROM  Sales.VEmpOrders ORDER BY empid, orderyear

--------------------------------------------------------------------------

USE [Northwinds2022TSQLV7]
GO

IF OBJECT_ID('Sales.VEmpOrder', 'V') IS NOT NULL
DROP VIEW Sales.VEmpOrder;
GO

CREATE OR ALTER VIEW [Sales].[VEmpOrder]
  WITH SCHEMABINDING
AS

SELECT
  o.EmployeeId,
  YEAR(O.OrderDate) AS OrderYear,
  SUM(OD.Quantity) AS Quantity
FROM [Sales].[Order] AS O
  JOIN [Sales].[OrderDetail] AS OD
    ON OD.OrderId = O.OrderId
GROUP BY 
  o.EmployeeId,
  YEAR(O.OrderDate);
GO

SELECT * FROM  Sales.VEmpOrder as o ORDER BY o.EmployeeId, o.OrderYear

**Chapter 05 - Table Expressions - Exercises**

**5.2**

```
-- Write a query against Sales.VEmpOrders
-- that returns the running qty for each employee and year
-- Tables involved: TSQLV6 database, Sales.VEmpOrders view

-- Desired output:
empid       orderyear   qty         runqty
----------- ----------- ----------- -----------
1           2020        1620        1620
1           2021        3877        5497
1           2022        2315        7812
2           2020        1085        1085
2           2021        2604        3689
2           2022        2366        6055
3           2020        940         940
3           2021        4436        5376
3           2022        2476        7852
4           2020        2212        2212
4           2021        5273        7485
4           2022        2313        9798
5           2020        778         778
5           2021        1471        2249
5           2022        787         3036
6           2020        963         963
6           2021        1738        2701
6           2022        826         3527
7           2020        485         485
7           2021        2292        2777
7           2022        1877        4654
8           2020        923         923
8           2021        2843        3766
8           2022        2147        5913
9           2020        575         575
9           2021        955         1530
9           2022        1140        2670
(27 rows affected)
```

### Proposition
This query calculates the running total of the `Quantity` column from the `Sales.[VEmpOrder]` view. It retrieves the `EmployeeId`, `OrderYear`, and calculates the running total (`runqty`) of `Quantity` for each `EmployeeId` and `OrderYear`. The running total is the sum of `Quantity` for all years up to and including the current `OrderYear` for each employee.

### Table and Columns used
- **Table**: `Sales.[VEmpOrder]` (used as `o` and `o2`)
- **Columns**: `EmployeeId`, `OrderYear`, `Quantity`

### Predicate
- The main query calculates the running total of `Quantity` for each `EmployeeId` and `OrderYear`, summing up the quantities for all years up to and including the current `OrderYear` for each employee.

### Explanation
1. **Main Query**: The main query selects `EmployeeId`, `OrderYear`, and a running total (`runqty`) for each `EmployeeId` and `OrderYear`. For each row, it calculates the sum of `Quantity` for all years up to and including the current `OrderYear` for each employee.

2. **Subquery**: The subquery calculates the running total (`SUM(o2.Quantity)`) for each `EmployeeId` in the `Sales.[VEmpOrder]` view (`o2`), where the `EmployeeId` is the same as the `EmployeeId` of the current row in the main query (`o2.EmployeeId = o.EmployeeId`) and the `OrderYear` is less than or equal to the `OrderYear` of the current row in the main query (`o2.OrderYear <= o.OrderYear`).

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
GO

SELECT 
    o.empid,
    o.orderyear,
    o.qty,
    (SELECT SUM(o2.qty)
    FROM Sales.[VEmpOrders] as o2
    WHERE o2.empid = o.empid AND o2.orderyear <= o.orderyear
    ) as runqty
FROM Sales.[VEmpOrders] as o
ORDER BY o.empid;

USE [Northwinds2022TSQLV7]
GO

SELECT 
    o.EmployeeId,
    o.OrderYear,
    o.Quantity,
    (SELECT SUM(o2.Quantity)
    FROM Sales.[VEmpOrder] as o2
    WHERE o2.EmployeeId = o.EmployeeId AND o2.OrderYear <= o.OrderYear
    ) as runqty
FROM Sales.[VEmpOrder] as o
ORDER BY o.EmployeeId;

**Chapter 05 - Table Expressions**

**SCHEMABINDING**

### Proposition
This script creates or alters a view named `Sales.USACusts` in the `TSQLV6` database. The view selects columns (`custid`, `companyname`, `contactname`, `contacttitle`, `address`, `city`, `region`, `postalcode`, `country`, `phone`, `fax`) from the `Sales.Customers` table for customers located in the USA (`country = N'USA'`).

### Table and Columns used
- **Table**: `Sales.Customers`
- **Columns**: `custid`, `companyname`, `contactname`, `contacttitle`, `address`, `city`, `region`, `postalcode`, `country`, `phone`, `fax`

### Predicate
- The view filters the rows from the `Sales.Customers` table where the `country` is equal to `'USA'`.

### Explanation
1. **Create or Alter View**: The script creates or alters the view `Sales.USACusts` with the `WITH SCHEMABINDING` option. This option binds the schema of the underlying tables to the view, ensuring that if the schema of the tables changes, the view becomes invalid and needs to be recompiled.

2. **Select Statement**: The view selects specific columns from the `Sales.Customers` table for customers located in the USA (`country = N'USA'`).

### Note
`SCHEMABINDING` ensures that a view stays synchronized with the underlying tables, preventing changes to the tables that would break the view.


<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
GO

CREATE OR ALTER VIEW Sales.USACusts WITH SCHEMABINDING
AS

SELECT
  custid, companyname, contactname, contacttitle, address,
  city, region, postalcode, country, phone, fax
FROM Sales.Customers
WHERE country = N'USA';
GO

SELECT * FROM Sales.USACusts ORDER BY custid;

USE [Northwinds2022TSQLV7]
GO

CREATE OR ALTER VIEW [Sales].[USACust] WITH SCHEMABINDING
AS

SELECT
    c.CustomerId, c.CustomerCompanyName, c.CustomerContactName, c.CustomerContactTitle, c.CustomerAddress,
    c.CustomerCity,c.CustomerRegion,c.CustomerPostalCode,c.CustomerCountry,c.CustomerPhoneNumber,c.CustomerFaxNumber
FROM [Sales].[Customer] as c
WHERE c.CustomerCountry = N'USA';
GO

SELECT * FROM [Sales].[USACust] ORDER BY CustomerId;

**Chapter 05 - Table Expressions**

**APPLY - 1**

### Proposition
This query performs a cross join between the `Sales.Shipper` and `HumanResources.Employee` tables in the `Northwinds2022TSQLV7` database. It selects the `ShipperId` from the `Sales.Shipper` table and the `EmployeeId` from the `HumanResources.Employee` table, generating a result set that combines every row from `Sales.Shipper` with every row from `HumanResources.Employee`.

### Tables and Columns Used
- **Tables**: `Sales.Shipper`, `HumanResources.Employee`
- **Columns**: `ShipperId` (from `Sales.Shipper`), `EmployeeId` (from `HumanResources.Employee`)

### Explanation
- **Cross Join**: A cross join, also known as a Cartesian join, combines each row from the first table with every row from the second table, resulting in a potentially large result set.

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
GO

SELECT S.shipperid, E.empid
FROM Sales.Shippers AS S
  CROSS JOIN HR.Employees AS E;

USE [Northwinds2022TSQLV7]
GO

SELECT S.ShipperId, E.EmployeeId
FROM [Sales].[Shipper] AS S
  CROSS JOIN [HumanResources].[Employee] AS E;

**Chapter 05 - Table Expressions**

**APPLY - 2**

### Proposition
This query uses a `CROSS APPLY` operator to combine each row from the `Sales.Shipper` table with each row from the `HumanResources.Employee` table in the `Northwinds2022TSQLV7` database. It selects the `ShipperId` from the `Sales.Shipper` table and the `EmployeeId` from the `HumanResources.Employee` table, creating a result set that pairs each shipper with each employee.

### Tables and Columns Used
- **Tables**: `Sales.Shipper`, `HumanResources.Employee`
- **Columns**: `ShipperId` (from `Sales.Shipper`), `EmployeeId` (from `HumanResources.Employee`)

### Explanation
- **CROSS APPLY**: The `CROSS APPLY` operator is similar to `CROSS JOIN`, but it is used with a table-valued function. In this case, it applies the `HumanResources.Employee` table as a table-valued function to each row of the `Sales.Shipper` table, combining them row by row.

### Note 
- CROSS APPLY works better on things that have `no simple` JOIN condition.



<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
GO

SELECT S.shipperid, E.empid
FROM Sales.Shippers AS S
  CROSS APPLY HR.Employees AS E;

USE [Northwinds2022TSQLV7]
GO

SELECT S.ShipperId, E.EmployeeId
FROM [Sales].[Shipper] AS S
  CROSS APPLY [HumanResources].[Employee] AS E;

**Chapter 05 - Table Expressions**

**APPLY - 3**

### Proposition
This query uses a `CROSS APPLY` operator to join each row from the `Sales.Customer` table with the top 3 orders (based on `OrderDate` and `OrderId` in descending order) from the `Sales.Order` table for each customer. It selects the `CustomerId` from the `Sales.Customer` table and the `OrderId` and `OrderDate` from the top 3 orders for each customer.

### Tables and Columns Used
- **Tables**: `Sales.Customer`, `Sales.Order`
- **Columns**: `CustomerId` (from `Sales.Customer`), `OrderId`, `OrderDate` (from `Sales.Order`)

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
GO
SELECT C.custid, A.orderid, A.orderdate
FROM Sales.Customers AS C
  CROSS APPLY
    (SELECT TOP (3) orderid, empid, orderdate, requireddate 
     FROM Sales.Orders AS O
     WHERE O.custid = C.custid
     ORDER BY orderdate DESC, orderid DESC) AS A;


USE [Northwinds2022TSQLV7]
GO
SELECT C.CustomerId, A.OrderId, A.OrderDate
FROM [Sales].[Customer] AS C
  CROSS APPLY
    (SELECT TOP (3) o.OrderId, o.EmployeeId, o.OrderDate, o.RequiredDate
     FROM [Sales].[Order] AS O
     WHERE O.CustomerId = C.CustomerId
     ORDER BY o.OrderDate DESC, o.OrderId DESC) AS A;

**Chapter 05 - Table Expressions**

**APPLY - 4**

### Proposition
This query uses a `CROSS APPLY` operator to join each row from the `Sales.Customer` table with the top 3 orders (based on `OrderDate` and `OrderId` in descending order) from the `Sales.Order` table for each customer. It selects the `CustomerId` from the `Sales.Customer` table and the `OrderId` and `OrderDate` from the top 3 orders for each customer.

### Tables and Columns Used
- **Tables**: `Sales.Customer`, `Sales.Order`
- **Columns**: `CustomerId` (from `Sales.Customer`), `OrderId`, `OrderDate` (from `Sales.Order`)

### Explanation
- **CROSS APPLY**: The `CROSS APPLY` operator is used to apply a subquery that retrieves the top 3 orders for each customer from the `Sales.Order` table. The subquery uses `OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY` to limit the results to the top 3 orders, ordered by `OrderDate` and `OrderId` in descending order.

### OFFSET-FETCH

**OFFSET-FETCH** is a feature in databases that helps in paging and limiting the number of rows returned by a query.


<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
-- With OFFSET-FETCH
USE [TSQLV6]
GO
SELECT C.custid, A.orderid, A.orderdate
FROM Sales.Customers AS C
  CROSS APPLY
    (SELECT orderid, empid, orderdate, requireddate 
     FROM Sales.Orders AS O
     WHERE O.custid = C.custid
     ORDER BY orderdate DESC, orderid DESC
     OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY) AS A;

USE [Northwinds2022TSQLV7]
GO
SELECT C.CustomerId, A.OrderId, A.OrderDate
FROM [Sales].[Customer] AS C
  CROSS APPLY
    (SELECT o.OrderId, o.EmployeeId, o.OrderDate, o.RequiredDate 
     FROM [Sales].[Order] AS O
     WHERE O.CustomerId = C.CustomerId
     ORDER BY o.OrderDate DESC, o.OrderId DESC
     OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY) AS A;

**Chapter 05 - Table Expressions**

**APPLY - 5**

### Proposition
This query uses an `OUTER APPLY` operator to join each row from the `Sales.Customer` table with the top 3 orders (based on `OrderDate` and `OrderId` in descending order) from the `Sales.Order` table for each customer. It selects the `CustomerId` from the `Sales.Customer` table and the `OrderId` and `OrderDate` from the top 3 orders for each customer.

### Tables and Columns Used
- **Tables**: `Sales.Customer`, `Sales.Order`
- **Columns**: `CustomerId` (from `Sales.Customer`), `OrderId`, `OrderDate` (from `Sales.Order`)

### Explanation
- **OUTER APPLY**: The `OUTER APPLY` operator is similar to `LEFT OUTER JOIN`,  it includes rows from the left table (`Sales.Customer` in this case) even if there are no matching rows in the right table (`Sales.Order`). This ensures that each customer from `Sales.Customer` is included in the result set, even if they have no orders.

<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
-- 3 most recent orders for each customer, preserve all customers
USE [TSQLV6]
GO
SELECT C.custid, A.orderid, A.orderdate
FROM Sales.Customers AS C
  OUTER APPLY
    (SELECT TOP (3) orderid, empid, orderdate, requireddate 
     FROM Sales.Orders AS O
     WHERE O.custid = C.custid
     ORDER BY orderdate DESC, orderid DESC) AS A;

USE [Northwinds2022TSQLV7]
GO
SELECT C.CustomerId, A.OrderId, A.OrderDate
FROM [Sales].[Customer] AS C
  OUTER APPLY
    (SELECT TOP (3) o.OrderId, o.EmployeeId, o.OrderDate, o.RequiredDate 
     FROM [Sales].[Order] AS O
     WHERE O.CustomerId = C.CustomerId
     ORDER BY orderdate DESC, orderid DESC) AS A;

**Chapter 05 - Table Expressions**

**APPLY - 6**

### Proposition
This script creates a scalar-valued function `dbo.TopOrder` in the `Northwinds2022TSQLV7` database. The function takes a `CustomerId` and a count `N` as input parameters and returns a table with the top `N` orders (based on `OrderDate` and `OrderId` in descending order) for the specified customer. The main query then uses a `CROSS APPLY` to join each row from the `Sales.Customer` table with the top 3 orders for each customer using the `dbo.TopOrder` function.

### Tables and Columns Used
- **Tables**: `Sales.Customer`, `Sales.Order`
- **Columns**: `CustomerId` (from `Sales.Customer`), `CustomerCompanyName` (from `Sales.Customer`), `OrderId`, `EmployeeId`, `OrderDate`, `RequiredDate` (from `Sales.Order`)

### Explanation
- **Function Creation**: The script first checks if the function `dbo.TopOrder` exists and drops it if it does. It then creates or alters the function to accept a `CustomerId` and a count `N`, and returns a table with the top `N` orders for the specified customer.
- **Function Usage**: The main query uses `CROSS APPLY` to apply the `dbo.TopOrder` function to each row from the `Sales.Customer` table, retrieving the top 3 orders for each customer.
- **Result Set**: The query generates a result set where each row contains the `CustomerId` and `CustomerCompanyName` from `Sales.Customer`, and the `OrderId`, `EmployeeId`, `OrderDate`, and `RequiredDate` from the top 3 orders for each customer.


<img src="https://static.vecteezy.com/system/resources/previews/022/841/114/non_2x/chatgpt-logo-transparent-background-free-png.png" alt="ChatGPT Logo" width="15" height="15"> Written in collaboration with ChatGPT from OpenAI to improve understanding and assist with the explanation of the query.

In [ ]:
USE [TSQLV6]
GO

IF OBJECT_ID('dbo.TopOrders', 'IF') IS NOT NULL
DROP FUNCTION dbo.TopOrders;
GO

CREATE OR ALTER FUNCTION dbo.TopOrders
  (@custid AS INT, @n AS INT)
  RETURNS TABLE
AS
RETURN
  SELECT TOP (@n) orderid, empid, orderdate, requireddate
  FROM Sales.Orders
  WHERE custid = @custid
  ORDER BY orderdate DESC, orderid DESC;
GO

SELECT
  C.custid, C.companyname,
  A.orderid, A.empid, A.orderdate, A.requireddate 
FROM Sales.Customers AS C
  CROSS APPLY dbo.TopOrders(C.custid, 3) AS A;

--------------------------------------------------------------

USE [Northwinds2022TSQLV7]
GO

IF OBJECT_ID('dbo.TopOrder', 'IF') IS NOT NULL
DROP FUNCTION dbo.TopOrder;
GO

CREATE OR ALTER FUNCTION dbo.TopOrder
  (@CustomerId AS INT, @N AS INT)
  RETURNS TABLE
AS
RETURN
  SELECT TOP (@N) o.OrderId, o.EmployeeId, o.OrderDate, o.RequiredDate
  FROM [Sales].[Order] as o
  WHERE o.CustomerId = @CustomerId
  ORDER BY o.OrderDate DESC, o.OrderId DESC;
GO

SELECT
  C.CustomerId, C.CustomerCompanyName,
  A.OrderId, A.EmployeeId, A.OrderDate, A.RequiredDate 
FROM [Sales].[Customer] AS C
  CROSS APPLY dbo.TopOrder(C.CustomerId, 3) AS A;